# install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# target 'MachoToolGUI' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   pod 'MachOTool', :path =>'../CLI'

# end
target 'MachoToolGUI' do
  use_frameworks!
  pod 'MachOTool', :path =>'../CLI'
end

 
